project:
  type: website
  output-dir: docs

website:
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  navbar:
    left: 
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      
format:
  html:
    theme: [cosmo, styles.scss]

